### ISSUE TITLE
SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.

### ISSUE THREAD

**Issue by dmitryusenko** [RonasIT/angular-common#14]
From time to time we receive the following error message in Sentry:

![error](https://user-images.githubusercontent.com/47531588/161035222-af9d0d1a-806d-45b9-86c7-31fdcc08c00c.png)

It looks like this exception is thrown when the `Block third-party cookies and site data` checkbox is set in browser's content settings.

I think this case should be handled by `angular-common` gracefully, hence I am opening this issue.

**Comment by dmitryusenko** [comment]
@astorozhevsky 

I think we should detect that `localStorage` and `sessionStorage` properties are unavailable and if that's the case, then we should avoid accessing them in methods such as **[getTokensFromStorage](https://github.com/RonasIT/angular-common/blob/master/common/src/auth/auth.service.ts#L177)**. Also, we could probably implement some fallback logic for these methods, for example some in-memory storage. What do you think?

**Comment by astorozhevsky** [comment]
@dmitryusenko could you please clarify if you were managed to reproduce this issue?

**Comment by dmitryusenko** [comment]
@astorozhevsky 

Yes, I was able to reproduce it in the latest Chrome. All you need to do to reproduce this issue is block third-party cookies completely in settings located here: `chrome://settings/cookies`, and then open any project that makes use of `AuthModule` provided by `angular-common`. The website crashes in this case and becomes completely unusable.

**Comment by astorozhevsky** [comment]
@dmitryusenko thanks! I've managed to reproduce this bug.

<img width="775" alt="Screenshot 2022-05-09 at 11 33 29" src="https://user-images.githubusercontent.com/11055414/167346584-f2f82058-471d-4994-8f87-c96f95af79df.png">

Can you please prepare PR to fix this bug?

**Comment by dmitryusenko** [comment]
@astorozhevsky Let's see if it gets resolved with https://github.com/RonasIT/angular-common/pull/16.
